### PR TITLE
RESIDE-30: First shot at a projects list

### PR DESCRIPTION
**Pull request by richfitz**
This is woefully incomplete, but I figure we should start somewhere.

I have included R packages that we have written blog posts for and/or that have been released to CRAN recently, along with VIMC as an obvious piece of work.

I feel that it would be better to get _something_ up and then iterate through adding new projects as needed than to try and curate a perfect list right away.  But if there are things you would like to add right away please edit the PR directly, include a blurb in a comment, or create new issues so we remember to add them later.

The structure here is purely a suggestion.  But I figure we have two modes of work: things done to order where the content will often be private (VIMC, things like first90) and reusable components.  But we could organise things in any other way and/or split across multiple pages once it grows. 

Things that off-hand I know of as missing include:

* the data collection app that Alex just updated this week
* the first90/shiny90 work
* orderly and orderlyweb
* the data vis tool
* the barman-in-the-cloud work (and in general a lot of our infrastructure work might warrant a space too)
* the cluster tools and wes' portal for the cluster

but there's lots more too

### CODE REVIEW

**Review by EmmaLRussell — CHANGES_REQUESTED** [review]
Looks good to me even if incomplete. Date needs fixing unless you're deliberately backdating this! Any scope for putting in any pretty pictures e.g. James's 'censored data vis tool' image?

**Review by weshinsley — APPROVED** [review]
I've appended a section at the bottom on Public Outreach tools - see what you think.

On the whole: I agree with earlier comments - once "something" is in place of this kind, it's up and running and can be refined incrementally. Eventually, the front page could become quite "catalogue"-ish, with perhaps some light categorisation, and links to a proper page for each - whether that's more reside pages, or github, or CRAN...

Anyway - for me, I think this is good enough to approve and go for a starter.

**Comment by richfitz** [comment]
I've updated the date.  Pictures could be added, but I think a full-blown page for the vimc work would be a place for that

**Review by hillalex — APPROVED** [review]
Thanks for getting this started! Added a bit about shiny90 and the data collection app https://github.com/reside-ic/reside-ic.github.io/pull/13/commits/5cb7e22fac0b2ee3523fc45320c81ad15fa8a475

**Pull request merged**
