### PR TITLE
reside-22: Add cinterpolate post

### PR DESCRIPTION
**Pull request by richfitz**

### CODE REVIEW

**Review by weshinsley — APPROVED** [review]
Looks good to me - one optional idea - 

I really like first para in your vignette saying essentially cinterpolate is like R's interpolate, but from C - I wonder if it may be good to put that thought in the first para as for me it kind of instantly nailed what we're about here.

I forget what sort of tagging we have, but it would be nice to be able to tag this as a "New Release" (trumpet fanfare), or a "Major/Minor Update", or, a policy document (like the PR one)... or a discussion...

**Review by weshinsley — APPROVED** [review]
(2nd try - Github ate my first with an error 500)
deleted - github is being really weird with me today... first approval seems to have worked!

**Comment by richfitz** [comment]
Thanks Wes - I had a hard time opening this post because it's pretty specific so I've tried your way and I think it's better.

We don't yet have a tagging system - I guess we can go back over posts and start tagging them once we see what we have.  But "releases" seems like an obvious category, yeah.  We should probably have more opinionated articles too 😁

**Comment by weshinsley** [comment]
You might want to trim down para 3 now, (the odin one), which talks about approx and spline again...

**Pull request merged**
